//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestFrind.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_answer
    {
        public Nullable<int> questionId { get; set; }
        public string answer { get; set; }
        public Nullable<int> userId { get; set; }
        public int Id { get; set; }
    
        public virtual quize_question quize_question { get; set; }
        public virtual user user { get; set; }
    }
}
