//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestFrind.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class quize_question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quize_question()
        {
            this.question_answer = new HashSet<question_answer>();
        }
    
        public string question { get; set; }
        public int Id { get; set; }
        public string answer { get; set; }
        public Nullable<int> quizeId { get; set; }
    
        public virtual quize quize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_answer> question_answer { get; set; }
    }
}
